# Generated by Django 4.2.7 on 2025-12-15 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('potential_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='builderprofile',
            name='customer_reviews',
        ),
        migrations.RemoveField(
            model_name='builderprofile',
            name='portfolio_images',
        ),
        migrations.AlterField(
            model_name='builderprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='investment_choice',
            field=models.CharField(choices=[('pending', 'Pending Decision'), ('self_invest', 'Landowner Invests'), ('builder_invest', 'Builder Invests')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='BuilderPortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='builder_portfolio/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('builder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_images', to='potential_app.builderprofile')),
            ],
        ),
    ]
